FROM krisfoster/graal-ee-ol-base:20.3.0-JDK11 AS builder

# Here I am using a private Docker image, built by myself, that contains
# the Enterprise Edition.
# I need to use this as support for G1GC is an Enterprise Edition Only feature

RUN mkdir app
COPY . /app
WORKDIR app

# Build the Jar
RUN /app/gradlew build

# Build the Native Image
RUN /app/gradlew nativeImage

FROM oraclelinux:8-slim
COPY --from=builder app/build/native-image/application app
ENTRYPOINT ["/app"]
